#节点过滤
#只保留地区为香港，美国，日本，台湾的节点
#只保留vip3的节点
#只保留倍率为0.5x——1x节点
#并且只保留iplc和cn2的节点
##以上四个条件必须同时为真，可根据机场节点的名称自行更改关键词。
include_remarks=(?i)(?=.*(iplc|cn2))(?=.*v3)(?=.*(香港|美国|日本|台湾))(?=.*\b(0\.5x|0\.[6-9]x|1x)\b)

#添加美国4x家宽节点
include_remarks=(?i)(?=.*(iplc|cn2))(?=.*v3)(?=.*(香港|美国|日本|台湾))(?:(?=.*\b(0\.5x|0\.[6-9]x|1x)\b)|(?=.*美国)(?=.*\b4x\b))
